name: Verify source code changes

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get changed source files or maven poms of all modules
      id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        files: |
          pom.xml
          .mvn/**
          plantuml-generator-util/pom.xml
          plantuml-generator-util/src/main/**
          plantuml-generator-util/src/test/**
          plantuml-generator-maven-plugin/pom.xml
          plantuml-generator-maven-plugin/src/main/**
          plantuml-generator-maven-plugin/src/test/**
          plantuml-generator-maven-plugin/src/it/**
    - name: Set up JDK
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/setup-java@v3      
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Analyze with SonarCloud
      run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=devlauer_plantuml-generator -Dsonar.organization=devlauer -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=${project.build.directory}/site/jacoco/jacoco.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        